return {
  name = "CC Miner V2",
  version = "2.1.0",
  schema = 3,
  repository = "nononoyuyuyu/CC_Miner",
  files = {
    "src/ccminer/lib/common.lua",
    "src/ccminer/lib/protocol.lua",
    "src/ccminer/lib/geo.lua",
    "src/ccminer/lib/quarry.lua",
    "src/ccminer/worker.lua",
    "src/ccminer/worker_parts/01.part",
    "src/ccminer/worker_parts/02.part",
    "src/ccminer/worker_parts/03.part",
    "src/ccminer/worker_parts/04.part",
    "src/ccminer/worker_parts/05.part",
    "src/ccminer/controller.lua",
    "src/ccminer/controller_parts/01.part",
    "src/ccminer/controller_parts/02.part",
    "src/ccminer/controller_parts/03.part",
    "src/ccminer/gps_host.lua",
    "src/ccminer/setup.lua",
    "src/ccminer/boot.lua",
    "src/ccminer/command.lua",
  },
}
