#!/usr/bin/env python3
"""Build a self-contained ComputerCraft installer for offline transfer."""

from __future__ import annotations

import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VERSION = "2.0.0"
RUNTIME_FILES = [
    ("src/ccminer/lib/common.lua", "lib/common.lua"),
    ("src/ccminer/lib/protocol.lua", "lib/protocol.lua"),
    ("src/ccminer/lib/quarry.lua", "lib/quarry.lua"),
    ("src/ccminer/worker.lua", "worker.lua"),
    ("src/ccminer/controller.lua", "controller.lua"),
    ("src/ccminer/setup.lua", "setup.lua"),
    ("src/ccminer/boot.lua", "boot.lua"),
    ("src/ccminer/command.lua", "command.lua"),
]


def lua_long_string(text: str) -> str:
    for equals_count in range(0, 16):
        equals = "=" * equals_count
        close = f"]{equals}]"
        if close not in text:
            return f"[{equals}[{text}]{equals}]"
    raise ValueError("Could not find a safe Lua long-string delimiter")


def main() -> None:
    embedded: list[str] = []
    digest = hashlib.sha256()
    for source, target in RUNTIME_FILES:
        content = (ROOT / source).read_text(encoding="utf-8")
        digest.update(source.encode("utf-8"))
        digest.update(b"\0")
        digest.update(content.encode("utf-8"))
        embedded.append(
            "  { target = %s, content = %s },"
            % (lua_long_string(target), lua_long_string(content))
        )

    template = f'''-- CC Miner V2 offline installer/updater
-- Generated by tools/build_offline_bundle.py. Do not edit this file directly.
-- Version: {VERSION}
-- Source digest: {digest.hexdigest()}
-- Usage: ccminer-offline.lua worker | controller | update

local args = {{ ... }}
local action = string.lower(tostring(args[1] or ""))
local VERSION = "{VERSION}"
local ROOT = "/ccminer"
local TEMP = "/ccminer.update"
local BACKUP = "/ccminer.backup"

local files = {{
{chr(10).join(embedded)}
}}

local function ensureDir(path)
  if not path or path == "" or fs.exists(path) then return end
  local parent = fs.getDir(path)
  if parent and parent ~= "" then ensureDir(parent) end
  fs.makeDir(path)
end

local function readFile(path)
  if not fs.exists(path) or fs.isDir(path) then return nil end
  local handle = fs.open(path, "r")
  if not handle then return nil end
  local text = handle.readAll()
  handle.close()
  return text
end

local function writeFile(path, text)
  ensureDir(fs.getDir(path))
  local handle = fs.open(path, "w")
  if not handle then return false, "Cannot write " .. path end
  handle.write(text)
  handle.close()
  return true
end

local function copyIfPresent(source, target)
  local text = readFile(source)
  if text then return writeFile(target, text) end
  return true
end

local function usage()
  print("CC Miner V2 offline installer " .. VERSION)
  print("  ccminer-offline.lua worker")
  print("  ccminer-offline.lua controller")
  print("  ccminer-offline.lua update")
end

if action == "" then action = turtle and "worker" or "controller" end
if action ~= "worker" and action ~= "controller" and action ~= "update" then usage(); return end
if action == "worker" and not turtle then error("Worker installation requires a turtle.", 0) end
if action == "controller" and turtle then print("Warning: controller role is normally installed on a computer.") end
if action == "update" and not fs.exists(ROOT .. "/config.db") then
  error("No existing installation found. Use worker or controller instead.", 0)
end

term.clear()
term.setCursorPos(1, 1)
print("CC MINER V2 OFFLINE " .. string.upper(action))
print("")

if fs.exists(TEMP) then fs.delete(TEMP) end
ensureDir(TEMP)

for index, file in ipairs(files) do
  write(("[%d/%d] %s ... "):format(index, #files, file.target))
  local ok, err = writeFile(TEMP .. "/" .. file.target, file.content)
  if not ok then fs.delete(TEMP); printError("FAILED"); error(err, 0) end
  local loader = loadstring or load
  local compiled, compileError = loader(file.content, "@" .. file.target)
  if not compiled then
    fs.delete(TEMP)
    printError("FAILED")
    error("Embedded file failed syntax validation: " .. file.target .. ": " .. tostring(compileError), 0)
  end
  print("OK")
end

local preserved = {{
  {{ ROOT .. "/config.db", TEMP .. "/config.db" }},
  {{ ROOT .. "/config.db.bak", TEMP .. "/config.db.bak" }},
  {{ ROOT .. "/data/state.db", TEMP .. "/data/state.db" }},
  {{ ROOT .. "/data/state.db.bak", TEMP .. "/data/state.db.bak" }},
  {{ ROOT .. "/data/ccminer.log", TEMP .. "/data/ccminer.log" }},
  {{ ROOT .. "/data/ccminer.log.1", TEMP .. "/data/ccminer.log.1" }},
}}
for _, pair in ipairs(preserved) do
  local ok, err = copyIfPresent(pair[1], pair[2])
  if not ok then fs.delete(TEMP); error("Cannot preserve existing data: " .. tostring(err), 0) end
end

if fs.exists(BACKUP) then fs.delete(BACKUP) end
if fs.exists(ROOT) then fs.move(ROOT, BACKUP) end
local moved, moveError = pcall(fs.move, TEMP, ROOT)
if not moved then
  if fs.exists(ROOT) then fs.delete(ROOT) end
  if fs.exists(BACKUP) then fs.move(BACKUP, ROOT) end
  error("Install swap failed: " .. tostring(moveError), 0)
end

print("")
if action == "update" then
  print("Offline update installed: " .. VERSION)
  print("Previous files: /ccminer.backup")
  print("Run: reboot")
else
  local setupOk = shell.run(ROOT .. "/setup.lua", action)
  if not setupOk then
    printError("Setup did not complete. Run: " .. ROOT .. "/setup.lua " .. action)
  else
    print("")
    print("Installation complete. Run: reboot")
  end
end
'''

    output = ROOT / "dist" / "ccminer-offline.lua"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(template, encoding="utf-8", newline="\n")
    print(f"Wrote {output.relative_to(ROOT)} ({output.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
