#!/usr/bin/env python3
"""Build a split, self-contained ComputerCraft installer for offline transfer."""

from __future__ import annotations

import argparse
import hashlib
import os
import shutil
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VERSION = "2.1.0"
PART_LIMIT_BYTES = 12_000
RUNTIME_FILES = [
    ("src/ccminer/lib/common.lua", "lib/common.lua"),
    ("src/ccminer/lib/protocol.lua", "lib/protocol.lua"),
    ("src/ccminer/lib/geo.lua", "lib/geo.lua"),
    ("src/ccminer/lib/quarry.lua", "lib/quarry.lua"),
    ("src/ccminer/worker.lua", "worker.lua"),
    ("src/ccminer/worker_parts/01.part", "worker_parts/01.part"),
    ("src/ccminer/worker_parts/02.part", "worker_parts/02.part"),
    ("src/ccminer/worker_parts/03.part", "worker_parts/03.part"),
    ("src/ccminer/worker_parts/04.part", "worker_parts/04.part"),
    ("src/ccminer/worker_parts/05.part", "worker_parts/05.part"),
    ("src/ccminer/controller.lua", "controller.lua"),
    ("src/ccminer/controller_parts/01.part", "controller_parts/01.part"),
    ("src/ccminer/controller_parts/02.part", "controller_parts/02.part"),
    ("src/ccminer/controller_parts/03.part", "controller_parts/03.part"),
    ("src/ccminer/gps_host.lua", "gps_host.lua"),
    ("src/ccminer/setup.lua", "setup.lua"),
    ("src/ccminer/boot.lua", "boot.lua"),
    ("src/ccminer/command.lua", "command.lua"),
]


def lua_long_string(text: str) -> str:
    for equals_count in range(16):
        equals = "=" * equals_count
        if f"]{equals}]" not in text:
            return f"[{equals}[{text}]{equals}]"
    raise ValueError("Could not find a safe Lua long-string delimiter")


def split_text(text: str, maximum_bytes: int) -> list[str]:
    """Split UTF-8 text on line boundaries without changing its contents."""
    parts: list[str] = []
    current: list[str] = []
    current_bytes = 0
    for line in text.splitlines(keepends=True):
        line_bytes = len(line.encode("utf-8"))
        if line_bytes > maximum_bytes:
            raise ValueError(f"A generated line exceeds the part limit: {line_bytes} bytes")
        if current and current_bytes + line_bytes > maximum_bytes:
            carry: list[str] = []
            while current and not current[-1].strip():
                blank = current.pop()
                current_bytes -= len(blank.encode("utf-8"))
                carry.insert(0, blank)
            if current:
                parts.append("".join(current))
            current = carry
            current_bytes = sum(len(item.encode("utf-8")) for item in carry)
            if current and current_bytes + line_bytes > maximum_bytes:
                parts.append("".join(current))
                current = []
                current_bytes = 0
        current.append(line)
        current_bytes += line_bytes
    if current:
        parts.append("".join(current))
    if "".join(parts) != text:
        raise AssertionError("Split output does not reproduce the source")
    if any(len(part.encode("utf-8")) > maximum_bytes for part in parts):
        raise AssertionError("Split output exceeds the part limit")
    return parts


def build_installer() -> str:
    embedded: list[str] = []
    digest = hashlib.sha256()
    for source, target in RUNTIME_FILES:
        content = (ROOT / source).read_text(encoding="utf-8")
        digest.update(source.encode("utf-8"))
        digest.update(b"\0")
        digest.update(content.encode("utf-8"))
        embedded.append(
            "  { target = %s, content = %s },"
            % (lua_long_string(target), lua_long_string(content))
        )

    return f'''-- CC Miner V2 offline installer/updater
-- Generated by tools/build_offline_bundle.py. Do not edit directly.
-- Version: {VERSION}
-- Source digest: {digest.hexdigest()}
-- Usage: ccminer-offline.lua worker | controller | gps | update

local args = {{ ... }}
local action = string.lower(tostring(args[1] or ""))
local VERSION = "{VERSION}"
local ROOT, TEMP, BACKUP = "/ccminer", "/ccminer.update", "/ccminer.backup"

local files = {{
{chr(10).join(embedded)}
}}

local function ensureDir(path)
  if not path or path == "" or fs.exists(path) then return end
  local parent = fs.getDir(path)
  if parent and parent ~= "" then ensureDir(parent) end
  fs.makeDir(path)
end
local function readFile(path)
  if not fs.exists(path) or fs.isDir(path) then return nil end
  local handle = fs.open(path, "r")
  if not handle then return nil end
  local text = handle.readAll(); handle.close(); return text
end
local function writeFile(path, text)
  ensureDir(fs.getDir(path))
  local handle = fs.open(path, "w")
  if not handle then return false, "Cannot write " .. path end
  handle.write(text); handle.close(); return true
end
local function copyIfPresent(source, target)
  local text = readFile(source)
  if text then return writeFile(target, text) end
  return true
end
local function moveChecked(source, target)
  local ok, moveError = pcall(fs.move, source, target)
  if not ok or not fs.exists(target) then
    return false, tostring(moveError or ("Move destination is missing: " .. target))
  end
  return true
end
local function compileFile(target)
  local compiled, compileError = loadfile(TEMP .. "/" .. target)
  if not compiled then
    fs.delete(TEMP)
    error("Embedded file failed syntax validation: " .. target .. ": " .. tostring(compileError), 0)
  end
end
local function compileParts(label, targets)
  local source = {{}}
  for index, target in ipairs(targets) do
    local text = readFile(TEMP .. "/" .. target)
    if not text then fs.delete(TEMP); error("Embedded runtime part is missing: " .. target, 0) end
    source[index] = text
  end
  local loader = loadstring or load
  local compiled, compileError = loader(table.concat(source), "@" .. label .. ".assembled.lua")
  if not compiled then
    fs.delete(TEMP)
    error("Assembled source failed syntax validation: " .. label .. ": " .. tostring(compileError), 0)
  end
end
local function usage()
  print("CC Miner V2 offline installer " .. VERSION)
  print("  ccminer-offline.lua worker")
  print("  ccminer-offline.lua controller")
  print("  ccminer-offline.lua gps")
  print("  ccminer-offline.lua update")
end

if action == "" then action = turtle and "worker" or "controller" end
if action ~= "worker" and action ~= "controller" and action ~= "gps" and action ~= "update" then usage(); return end
if action == "worker" and not turtle then error("Worker installation requires a turtle.", 0) end
if action == "update" and not fs.exists(ROOT .. "/config.db") then error("No existing installation found.", 0) end

term.clear(); term.setCursorPos(1, 1)
print("CC MINER V2 OFFLINE " .. string.upper(action)); print("")
if fs.exists(TEMP) then fs.delete(TEMP) end
ensureDir(TEMP)
for index, file in ipairs(files) do
  write(("[%d/%d] %s ... "):format(index, #files, file.target))
  local ok, err = writeFile(TEMP .. "/" .. file.target, file.content)
  if not ok then fs.delete(TEMP); printError("FAILED"); error(err, 0) end
  print("OK")
end

for _, target in ipairs({{
  "lib/common.lua", "lib/protocol.lua", "lib/geo.lua", "lib/quarry.lua",
  "worker.lua", "controller.lua", "gps_host.lua", "setup.lua", "boot.lua", "command.lua",
}}) do
  compileFile(target)
end
compileParts("worker", {{
  "worker_parts/01.part", "worker_parts/02.part", "worker_parts/03.part",
  "worker_parts/04.part", "worker_parts/05.part",
}})
compileParts("controller", {{
  "controller_parts/01.part", "controller_parts/02.part", "controller_parts/03.part",
}})

local preserved = {{
  {{ ROOT .. "/config.db", TEMP .. "/config.db" }},
  {{ ROOT .. "/config.db.bak", TEMP .. "/config.db.bak" }},
  {{ ROOT .. "/data/state.db", TEMP .. "/data/state.db" }},
  {{ ROOT .. "/data/state.db.bak", TEMP .. "/data/state.db.bak" }},
  {{ ROOT .. "/data/ccminer.log", TEMP .. "/data/ccminer.log" }},
  {{ ROOT .. "/data/ccminer.log.1", TEMP .. "/data/ccminer.log.1" }},
}}
for _, pair in ipairs(preserved) do
  local ok, err = copyIfPresent(pair[1], pair[2])
  if not ok then fs.delete(TEMP); error("Cannot preserve existing data: " .. tostring(err), 0) end
end
if fs.exists(BACKUP) then fs.delete(BACKUP) end
local hadRoot = fs.exists(ROOT)
if hadRoot then
  local backedUp, backupError = moveChecked(ROOT, BACKUP)
  if not backedUp then fs.delete(TEMP); error("Cannot back up existing installation: " .. backupError, 0) end
end
local moved, moveError = moveChecked(TEMP, ROOT)
if not moved then
  if fs.exists(ROOT) then pcall(fs.delete, ROOT) end
  local restored, restoreError = true, nil
  if hadRoot then
    if fs.exists(BACKUP) then restored, restoreError = moveChecked(BACKUP, ROOT)
    else restored, restoreError = false, "Backup directory is missing." end
  end
  if not restored then
    error("Install swap failed and rollback failed. Previous files remain at " .. BACKUP .. ": "
      .. tostring(moveError) .. "; rollback: " .. tostring(restoreError), 0)
  end
  error("Install swap failed; previous installation was restored: " .. tostring(moveError), 0)
end
print("")
if action == "update" then
  print("Offline update installed: " .. VERSION); print("Previous files: /ccminer.backup"); print("Run: reboot")
else
  local setupOk = shell.run(ROOT .. "/setup.lua", action)
  if not setupOk then printError("Setup did not complete. Run: " .. ROOT .. "/setup.lua " .. action)
  else print(""); print("Installation complete. Run: reboot") end
end
'''


def render_bundle() -> tuple[list[str], list[str], str]:
    installer = build_installer()
    parts = split_text(installer, PART_LIMIT_BYTES)
    name_width = max(2, len(str(len(parts))))
    names = [f"{index:0{name_width}d}.part" for index in range(1, len(parts) + 1)]
    lua_names = "\n".join(f'  "{name}",' for name in names)
    loader = f'''-- CC Miner V2 split offline installer loader
-- Keep the adjacent ccminer-offline.parts directory when transferring this file.
local partNames = {{
{lua_names}
}}
local running = shell and shell.getRunningProgram and shell.getRunningProgram() or "ccminer-offline.lua"
local base = fs.getDir(running)
local partDir = fs.combine(base, "ccminer-offline.parts")
local source = {{}}
for index, name in ipairs(partNames) do
  local path = fs.combine(partDir, name)
  local handle = fs.open(path, "r")
  if not handle then error("Missing offline installer part: " .. path, 0) end
  source[index] = handle.readAll()
  handle.close()
end
local loadSource = loadstring or load
local program, compileError = loadSource(table.concat(source), "@ccminer-offline.assembled.lua")
if not program then error("Cannot assemble offline installer: " .. tostring(compileError), 0) end
return program(...)
'''
    return parts, names, loader


def check_outputs(parts: list[str], names: list[str], loader: str) -> None:
    dist = ROOT / "dist"
    parts_dir = dist / "ccminer-offline.parts"
    output = dist / "ccminer-offline.lua"
    actual_names = sorted(path.name for path in parts_dir.glob("*.part")) if parts_dir.is_dir() else []
    if actual_names != names:
        raise SystemExit(
            "Offline bundle is stale: part list differs. Run: python tools/build_offline_bundle.py"
        )
    for name, expected in zip(names, parts):
        if (parts_dir / name).read_bytes() != expected.encode("utf-8"):
            raise SystemExit(
                f"Offline bundle is stale: {name} differs. Run: python tools/build_offline_bundle.py"
            )
    if not output.is_file() or output.read_bytes() != loader.encode("utf-8"):
        raise SystemExit(
            "Offline bundle is stale: loader differs. Run: python tools/build_offline_bundle.py"
        )
    total = sum(len(part.encode("utf-8")) for part in parts)
    print(f"Offline bundle is current ({len(parts)} parts, {total} assembled bytes).")


def write_outputs(parts: list[str], names: list[str], loader: str) -> None:

    dist = ROOT / "dist"
    parts_dir = dist / "ccminer-offline.parts"
    output = dist / "ccminer-offline.lua"
    dist.mkdir(parents=True, exist_ok=True)
    backup_dir = dist / ".ccminer-offline.parts.previous"
    if backup_dir.exists():
        shutil.rmtree(backup_dir)

    with tempfile.TemporaryDirectory(prefix=".ccminer-offline.", dir=dist) as temporary:
        stage = Path(temporary)
        stage_parts = stage / "ccminer-offline.parts"
        stage_parts.mkdir()
        for name, part in zip(names, parts):
            (stage_parts / name).write_text(part, encoding="utf-8", newline="\n")
        stage_loader = stage / "ccminer-offline.lua"
        stage_loader.write_text(loader, encoding="utf-8", newline="\n")

        had_parts = parts_dir.exists()
        if had_parts:
            os.replace(parts_dir, backup_dir)
        try:
            os.replace(stage_parts, parts_dir)
            os.replace(stage_loader, output)
        except Exception:
            if parts_dir.exists():
                shutil.rmtree(parts_dir)
            if had_parts and backup_dir.exists():
                os.replace(backup_dir, parts_dir)
            raise
        if backup_dir.exists():
            shutil.rmtree(backup_dir)

    total = sum(len(part.encode("utf-8")) for part in parts)
    print(
        f"Wrote {output.relative_to(ROOT)} and {len(parts)} parts "
        f"({total} assembled bytes; each <= {PART_LIMIT_BYTES})"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if tracked dist files are stale")
    args = parser.parse_args()
    parts, names, loader = render_bundle()
    if args.check:
        check_outputs(parts, names, loader)
    else:
        write_outputs(parts, names, loader)


if __name__ == "__main__":
    main()
